### ISSUE TITLE
会場提供者のPRタイムの導入について

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#10]
## 背景
イベントを行う会場(もくもく会、LT会)について、ある程度の人数を収容可能なスペース利用に対する金額を考えると、会社さんの会場提供が非常にありがたい

その前提であるため会場提供してくださる方を増やしていきたい。当然ながら会場候補は多い方がもくもく会の継続的に開催につながる。また、会場が変われば毎回新鮮な印象になり参加者も嬉しいはず(いろんな会社さんのオフィスいきたいやん？）

## 考えたいこと

とはいうものの会場提供は、「その会社さんのご好意+準備コストが前提」であるため、それに対するリターンは運営として用意したい。

なので **「会場提供者のPRタイムの導入について」** を作りたい

PRタイムの内容は、以下のざっくりしたイメージです。

- 会の最初に行う
- ５分程度
- 好きに話して良い(会社紹介、We are hiring!　など)

## 決めたいこと

- 会場提供者のPRタイムを作るか/作らないか

## 補足

背景、その理由について補足や修正があればコメントください

**Comment by yumechi** [comment]
会場提供者のPRタイムの導入は賛成です。（背景や内容についても問題なしです）ただ、会の最後のほうが印象に残るので、会社の紹介は最後がいいかな。

会の最初に会場注意とともに触れてもらうスタイルでもOKですけど。

**Comment by Ushinji** [comment]
> 会の最後のほうが印象に残るので、会社の紹介は最後がいいかな。

最初より最後の方が参加率高い(遅刻してくる人など)もあるし、会の最後の方が確かにいいですねー

**Comment by Ushinji** [comment]
これもDONEで
