### ISSUE TITLE
もくもく会の「最初/最後にて全体で行うタイム」の再考

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#11]
## 議題

人数もある程度いるので、最初のガイダンス、最後の成果共有の時間をどうやって進めるか考えた方がよいと感じた。

ここはもう一度みなで考えたい。

**Comment by yumechi** [comment]
最初

* 会場注意: 3分
* 自己紹介＋やること宣言: 1分 × 人数

最後

* やれたこと宣言: 2分 × 人数
* 会場提供会社の紹介: 5分

がいいです。

基本的にやること、やったことを共有してここまでできた！ できなかった！を明確にしつつ、やれたことについてはみんなで褒め会える文化が僕はいいと思っています。なので、最後のやれたこと宣言は削ってほしくないですね。

一方で本質作業でないところに時間をかけるのは参加者の気持ち的によくないかな、と思っていてこれ以上の時間を取るのは無しだと考えています。

**Comment by Ushinji** [comment]
## 質問
> 最初：自己紹介＋やること宣言: 1分 × 人数

> 最後：やれたこと宣言: 2分 × 人数

ここ質問なのですが、今回15人の参加者がいますが、全員が話すのってどう思いますか？
こちらについてメリット/デメリットがあると思っていて

## 全員1人ずつ話す

**メリット**
* 参加者全員が、全員の成果を少しでも知ることができる
* 成果を少しでも知れれば、あとで会話のきっかけになる

**デメリット**
* 単純に15人を聞き続けるのが長くてダレる可能性が
* 1人あたりの話す時間が少ない

それに対して、別のアプローチとして **「グループを作る」** という選択肢もあると思います

## グループを作る

例えば、4人グループを作るとして、

> 最初：自己紹介＋やること宣言: 2~3分ぐらい × 人数(10分)
> 最後：やれたこと宣言: 5分 × 人数(20分)

**メリット**
* 一人当たりのアウトプット時間が増える
* 聞いたことに対する質問といったリアクションができる

**デメリット**
* 他グループの状況を知ることができない

## じゃぁどうすんの？

で決めるべきことは前者と後者がどっちが優れているかという話ではなく、大事なのが **もくもく会がどういう方向性でいきたいのか** だと書いていて思いました。

* もくもく会の成果の詳しい内容は、個人のブログアウトプットやその後の懇親会での会話に任せる。なので、もくもく会では「何をやったか」を全員に共有することに重きを置く
  * この場合、前者のフォーマットが適切だと思います

* もくもく会の作業時間で出した成果を、その場で少しでも多くみんなにフィードバック貰いたい！、相手のアウトプットを知りたい！そこまでがもくもく会だ！
  * この場合、後者のフォーマットがより適していると思います

で、もくもく会ってどういう方向性なんすかね？

**Comment by yumechi** [comment]
アプローチいいですね。グループ作るのもありだと思う。僕は折衷案を考えました。

> もくもく会の作業時間で出した成果を、その場で少しでも多くみんなにフィードバック貰いたい！、相手のアウトプットを知りたい！そこまでがもくもく会だ！
> この場合、後者のフォーマットがより適していると思います

こっち派です。


感覚が逆で15人って超少ないし、はじめの自己紹介は全員でやればいいと思ってた。で、はじめのやりたいことは全員言えばいいかなって。
初めての人も多いし顔合わせはちゃんとしたほうがいいと思います。せっかく一緒に集まった人たちなので、出会いを大切にしたいなーと。


結果報告は逆にダレそうな気もしていて、グループでいいかなと。興味持ってそうな人たちで固めたりしたほうがいいのかなーって思ってます。


終了15分くらい前に成果発表やります、全員でやると時間かかると思うので、グループでやりましょ、聞きたい人のところ行こう。でいいんじゃないかなーと考えます。
で、興味のある人同士でフィードバック得てみるのが良いかなとか。

**Comment by Ushinji** [comment]
> 初めての人も多いし顔合わせはちゃんとしたほうがいいと思います。せっかく一緒に集まった人たちなので、出会いを大切にしたいなーと。

ここは共感ですね。また、互いが分からない同士では、会話や質問するにもハードルあるので、自己紹介は全員でした方が結果的に全体の満足度は良くなるかと思います。

> 成果発表やります、全員でやると時間かかると思うので、グループでやりましょ、聞きたい人のところ行こう。でいいんじゃないかなーと考えます。で、興味のある人同士でフィードバック得てみるのが良いかなとか。

なるほどー

アウトプットタイム的な感じにするのではなく、立食の懇親会のような形で自由に自分が聞きたいところに聞きに行く感じで、そこで互いのアウトプットで交流する感じですかね？？

それとも、「俺はフロントエンドやったから、フロントエンド関連に興味あるやつ集合ーーーー」みたいにグループするイメージですかね？

それとも、運営側が初めに参加者が発表した今日やることを元に、ある程度分類してグルーピングするか。

**Comment by yumechi** [comment]
> それとも、「俺はフロントエンドやったから、フロントエンド関連に興味あるやつ集合ーーーー」みたいにグループするイメージですかね？

このイメージで、そこまでガッツリ決めなくても、人数的に当日適当にやるで回ると思う。


事前アンケートで聞いてやるのは運営コスト上がるので、やりたくないですね。

**Comment by Ushinji** [comment]
だいたいまとまった感じですかね。

# 会のスタート
## 開始
- はじめに/会場注意：5分
- 自己紹介＋やること宣言: 1分 × 人数：15分

- もくもく(13:20〜18:10)

## 終了 
- 全体共有会(18:10〜18:30)
  - 各自が自由に動いて互いのアウトプットを共有
  - ここは運営が自発的に行動することなし
- クロージング
  - 会場提供者トーク(18:30〜18:35)
  - 締めの言葉・撤収案内(18:35〜18:40)
- 会場撤収(18:40〜18:50)
- 退出

**Comment by Ushinji** [comment]
これDONEでいいですかね
