### ISSUE TITLE
twitterでの通知について

### ISSUE THREAD

**Issue by GOD-oda** [teckup-tokyo/MokuMoku#12]
アカウントの管理については他のissueで議論中だけど、もくもく会の告知とかインフォ系の通知とかにtwitter使った方がよさそう？とか思いまして。
で、誰がやるかはまた議論なんだけど、どうですかね？
現状、twitterのアカウントについては僕と平尾さんが管理できるヒトになってます。

**Comment by yutonihei** [comment]
タスク分散的な意味で、誰やるはTwitter権限持ってる人にお願いしてもらった方が良いと思われます

**Comment by GOD-oda** [comment]
なるほど！
例えば告知系は僕でも文章貰えれば流せますが、質問とかそういうのは対応出来ないんじゃないかと思って。僕がその場にいないから。

**Comment by yutonihei** [comment]
告知自体は貴族会からで、当日の相談とかは貴族会にリプライきたらほかの人が自分のアカウントとかで回答すればいいんじゃないかなと思います！

**Comment by GOD-oda** [comment]
なるほどですね！

**Comment by yumechi** [comment]
なんかこの辺もう少し上のレイヤで考えたいけど、貴族会アカウント向けにリプライきたら自分のアカウントでとっとと回答する運用のほうが問題解決速度が速いし、そうしましょう。
