### ISSUE TITLE
[某会第2回] もくもく会の振り返り 

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#16]
第二回もくもく会も無事終了しました！みなさまお疲れ様でした！

せっかくなので、振り返りをして、会をよりよくしていきましょう！
振り返りの形式ですが、KPT形式でお願いします！

**Comment by Ushinji** [comment]
## Keep
* Conpassページを突発ではなく、前もって公開(２週間前にやった：1/16)
* 最初のガイダンス、最後のクロージングの時間を作って、ちゃんと会として成立させる
    * グダグダなまま始まったり、終わらせたりしない
* 会場提供者LTの時間を作った

## Good
* 参加者が多くてよかった(14人)
    * 前日/当日キャンセル：5人
* slack、twitterに今日やったことを呟くよう促したら、一部やってくれている人がいてよかった
* 2回目なので、Conpassページ公開、開催するだけなら、ノウハウは溜まったと感じる
    * テンプレート化可能なので、やりますね

## Problem
* 最初自己紹介の時間作ったのですが、後から来た人のフォローをどうしようか。。。
* Slackチャンネル活用するのもいいけど、twitterの方が良くない？と思った
    * 個人的に、slackチャンネル１つしかないので、ここにみんなが進捗とか書きこむとメッセージが流れて嫌だなーと思いました
        * なので、自分のtwitterにハッシュタグつけて投げてました(まさかの運営が率先して違うことをするという…)
    * 貴族会常連でtimesチャンネルを作っている人はそこに好きに書き込んでフォローもらえる流れは凄く良いと思うのですが、それがない人はチャンネルに投稿するのハードルあるなと感じた。
    * あと、slackチャンネルに投稿するとクローズドですが、自分のtwitterに投稿する方がパブリック情報なので、結局自分のためになるという。後で振り返られるし、こんなことやっていますというアピールにもなる(使うかどうかは置いといて)
* 建物に入ってから、もくもく会会場までの導線で、迷ったという意見をいただく
    * 動線が作りが弱かったです。すいません。
    * 途中から動線変えたのですが看板が足りなくなって、外で自分が看板代わりの受付していました


## その他分かったこと、感じたこと
* もくもく会では、思った以上に自分の作業に集中して作業をすること
* Goodにも書いたのですが、もくもく会を開催するだけなら僕らはできるので、もくもく会をどう運営していくか(対外的にどう発信していくかなど）を考えたいと感じた
    * 内輪でやるの？対外的に流入を増やすの？なんの目的で？中にいる人が楽しめたらいいの？誰のためのコミュニティなの？とかとか
* その辺りの方針がないと、意思決定できないというか、議論が無駄に時間がかかって意味ない状況になるなぁと感じました

**Comment by IkezoeMakoto** [comment]
## Keep
* 特にトラブルなく完遂できた
* 結構な人数が集まり、当日キャンセルもほぼなく実施できた
* (参加者として)とても満足度の高いイベントだった
    * 集中して作業できたので、進捗が出た
* 懇親会などで交流も深められた
* 会場提供LTできた
* 各種告知もいい感じにやってくれていた
* (知る限り)ほぼ宇山さん一人のマンパワーだけでかなり質が高いイベントだった

## Problem & Try
* タスクが一人によりがち
    * -> とりあえず私も次回から運営手伝います
    * 運営やってみたい人を参加者の中から公募してもいいと思った
* 途中参加者の把握、フォローが少しできていなかった？
    * -> 要議論
* 雑談はどこまでOKとするか、場合によってはもう少しお互いに相談しあったりとかあってもよかったかも
    * -> 要議論
    * 例えばテーブルないで軽く雑談をしたり、タイムテーブル自体で前半後半と切ってもいいかも（５時間も集中は人間には不可能なので）
* 成果報告の場、フォーマットを決めて積極的に対外的にアウトプットしてもいいかも
* 全体共有事項は、どこかわかる所にまとめて書いておくといい
    * 途中から前のホワイトボードに書いてた
    * ネットワークの接続情報や、タイムスケジュール、お手洗い、飲食について、スラックチャンネルハッシュタグなど
* 今回はなかったように思うが、もくもく会にきたはいいけど何しよう、みたいな人もいるので一緒にもくもくできるテーマがあったりしてもいいかも
    * React tutorialやる、railsチュートリアルやる、◯◯機能を作ってみる、〜〜の本、記事を読んでみる、など
* (多分今回は宇山さんがほぼ一人でやってくれたからというのもあると思いますが)全体のマイルストンの可視化が足りていない
    * いつまでにコンパスページを作り、いつ公開し、いつまでに懇親会の人数をFIXし、予約を取り、リマインド通知を出し、会を実施し、振り返りをやり、次回開催の準備はいつまでにやるのか
    * ここまでをワンセットとしてイテレータブルにしておくことで会の実施はだいぶ楽になり、運営そのものに手をかけずに済むようになり、運営の質を高めるための企画をできるようになるかと思います。

>Goodにも書いたのですが、もくもく会を開催するだけなら僕らはできるので、もくもく会をどう運営していくか(対外的にどう発信していくかなど）を考えたいと感じた

完全に同意です。

**Comment by IkezoeMakoto** [comment]
遅くなってしまい申し訳ないです！振り返り書いておきました。
振り返り内容を受けてのネクストアクション等はいつまでに考えますか？
議論も一部必要だと思ってるので、場合によってはどこかで集まったりして話した方がいいのかなと思っています。

**Comment by Ushinji** [comment]
せやな。ネクストアクションも決めましょう。
とりあえず一旦みんなの振り返りが出揃ってからで！

KPTについては、今週の土曜(2/9(土) 23:59)までにしますね。１週間以内で。

**Comment by yumechi** [comment]
## KEEP

* 開催できた
* いい感じに最後内容の共有ができた、グループ同士でやるのがちょうどいいとわかった（全体だと長過ぎる）
* オープニングは知らないけど、クロージングはちゃんと閉められた
* キャンセル率が低い

## Good

* 有志で場所までの写真を上げてくれた人がいた
* もともと貴族会以外から来てくれる人も多々いた
* あとからでも入りやすい感じ、豊富な電源

## Problem

* 想定より募集時点での人数きすぎた感じはする
    * 他の場所考える？
    * 来てくれた人がなんのつながりだったかの手がかりは調べたい
* 第2回だが前回並に準備に時間がかかったような
    * 印象だけ
* Slackチャンネル運用は割と限界
    * 運営側の前回のログもすでになくて経緯が辿れない
    * 相談事は別のワークスペースとかDiscordとかに逃げるパターンも有り
    * 単なるできました！とかはツイッターとかでいいんじゃないの
    * この辺他のイベントもそうだけど、ツールの使い分けが全体的にできてないように思う

## Try

* コミュニケーションツールの模索はしたいな(ちょいちょい言ってたけど別ワークスペースのほうがマシな気がしてる)
* あと対外的にできる成果をこちらでもまとめるフローはそろそろ考えないと

## 完全な私見

* twitter やってない人はどうするんだろう（twitterをやってないひとちらちら見る）
* 開催するのはできるけど、開催を楽にする・会の質を高めるための取り組みや工夫はもうちょいできるはず
* もくもく会に作業無し・目的無しで来る人を想定できないないんですが、過去事例があればプライベートなところでもいいので共有がほしいです（こういう人は想定しなくていいんじゃないんですかね（作業する場所に作業を持ってこないのは謎で怪しいため）、という話は結構前にしていたが、ログも残ってないし改めて考えてもいいかもしれないかもなあと思いつつ、そういう人たちって自分から手を上げるんじゃない？ って気もしてるし、作業内容をこちらから提示するモデルはなんか違う気がする）
* 一緒に作業した人たちが今後もつながっていくような設計にしたいなあとかぼんやり思う。ぼにゃ。

**Comment by yumechi** [comment]
この辺割と解決されてそう
https://github.com/kizokukai/MokuMoku/issues/4#issuecomment-431637995

**Comment by Ushinji** [comment]
ネクストアクションを考えるにあたって、とりあえず、KeepとGoodをまとめますね。

## Keep
### 開催できた系
  * 開催できた
  * 特にトラブルなく完遂できた

### Conpass公開
  * Conpassページを突発ではなく、前もって公開(２週間前にやった：1/16)
  * 2回目なので、Conpassページ公開、開催するだけなら、ノウハウは溜まったと感じる
    * テンプレート化可能なので、やりますね

### 始めと終わりの時間を作ること
  * 最初のガイダンス、最後のクロージングの時間を作って、ちゃんと会として成立させる
  * オープニングは知らないけど、クロージングはちゃんと閉められた
  * いい感じに最後内容の共有ができた、グループ同士でやるのがちょうどいいとわかった（全体だと長過ぎる）
  * 各種告知もいい感じにやってくれていた

### 会場提供者LTの時間を作ること
  * 会場提供者LTの時間を作った
  * 会場提供LTできた


### 当日の参加率
  * 結構な人数が集まり、当日キャンセルもほぼなく実施できた
  * キャンセル率が低い
  * 参加者が多くてよかった(14人)
    * 前日/当日キャンセル：5人

### Conpass経由での流入
  * もともと貴族会以外から来てくれる人も多々いた


### 交流会
  * 懇親会などで交流も深められた


### その他
  * (参加者として)とても満足度の高いイベントだった
    * 集中して作業できたので、進捗が出た

## Good
* slack、twitterに今日やったことを呟くよう促したら、一部やってくれている人がいてよかった
* 2回目なので、Conpassページ公開、開催するだけなら、ノウハウは溜まったと感じる
  * (知る限り)ほぼ宇山さん一人のマンパワーだけでかなり質が高いイベントだった
* 有志で場所までの写真を上げてくれた人がいた
* あとからでも入りやすい感じ、豊富な電源

**Comment by Ushinji** [comment]
Problemのまとめ。
補足として、「思ったこと、わかったこと」もProblemにまとめています。

## Problem
### 今後の情報共有手段の運用について
* Slackチャンネル活用するのもいいけど、twitterの方が良くない？と思った
    * 個人的に、slackチャンネル１つしかないので、ここにみんなが進捗とか書きこむとメッセージが流れて嫌だなーと思いました
        * なので、自分のtwitterにハッシュタグつけて投げてました(まさかの運営が率先して違うことをするという…)
    * 貴族会常連でtimesチャンネルを作っている人はそこに好きに書き込んでフォローもらえる流れは凄く良いと思うのですが、それがない人はチャンネルに投稿するのハードルあるなと感じた。
    * あと、slackチャンネルに投稿するとクローズドですが、自分のtwitterに投稿する方がパブリック情報なので、結局自分のためになるという。後で振り返られるし、こんなことやっていますというアピールにもなる(使うかどうかは置いといて)
* Slackチャンネル運用は割と限界
    * 運営側の前回のログもすでになくて経緯が辿れない
    * 相談事は別のワークスペースとかDiscordとかに逃げるパターンも有り
    * 単なるできました！とかはツイッターとかでいいんじゃないの
    * この辺他のイベントもそうだけど、ツールの使い分けが全体的にできてないように思う
* twitter やってない人はどうするんだろう（twitterをやってないひとちらちら見る）
<br />

### 途中参加の人へのフォロー
* 最初自己紹介の時間作ったのですが、後から来た人のフォローをどうしようか。。。
* 途中参加者の把握、フォローが少しできていなかった？
    * -> 要議論
* 全体共有事項は、どこかわかる所にまとめて書いておくといい
    * 途中から前のホワイトボードに書いてた
    * ネットワークの接続情報や、タイムスケジュール、お手洗い、飲食について、スラックチャンネルハッシュタグなど
<br />

### もくもく会のコンテンツについて
* 雑談はどこまでOKとするか、場合によってはもう少しお互いに相談しあったりとかあってもよかったかも
    * -> 要議論
    * 例えばテーブルないで軽く雑談をしたり、タイムテーブル自体で前半後半と切ってもいいかも（５時間も集中は人間には不可能なので）
* 今回はなかったように思うが、もくもく会にきたはいいけど何しよう、みたいな人もいるので一緒にもくもくできるテーマがあったりしてもいいかも
    * React tutorialやる、railsチュートリアルやる、◯◯機能を作ってみる、〜〜の本、記事を読んでみる、など
* もくもく会に作業無し・目的無しで来る人を想定できないないんですが、過去事例があればプライベートなところでもいいので共有がほしいです（こういう人は想定しなくていいんじゃないんですかね（作業する場所に作業を持ってこないのは謎で怪しいため）、という話は結構前にしていたが、ログも残ってないし改めて考えてもいいかもしれないかもなあと思いつつ、そういう人たちって自分から手を上げるんじゃない？ って気もしてるし、作業内容をこちらから提示するモデルはなんか違う気がする）
* 一緒に作業した人たちが今後もつながっていくような設計にしたいなあとかぼんやり思う。ぼにゃ。
<br />

### 対外的な広報について
* 成果報告の場、フォーマットを決めて積極的に対外的にアウトプットしてもいいかも
<br />

### もくもく会運営について
* タスクが一人によりがち
    * -> とりあえず私も次回から運営手伝います
    * 運営やってみたい人を参加者の中から公募してもいいと思った

* (多分今回は宇山さんがほぼ一人でやってくれたからというのもあると思いますが)全体のマイルストンの可視化が足りていない
    
* いつまでにコンパスページを作り、いつ公開し、いつまでに懇親会の人数をFIXし、予約を取り、リマインド通知を出し、会を実施し、振り返りをやり、次回開催の準備はいつまでにやるのか
    * ここまでをワンセットとしてイテレータブルにしておくことで会の実施はだいぶ楽になり、運営そのものに手をかけずに済むようになり、運営の質を高めるための企画をできるようになるかと思います。
* 想定より募集時点での人数きすぎた感じはする
    * 他の場所考える？
    * 来てくれた人がなんのつながりだったかの手がかりは調べたい
* 第2回だが前回並に準備に時間がかかったような
    * 印象だけ
* 開催するのはできるけど、開催を楽にする・会の質を高めるための取り組みや工夫はもうちょいできるはず
* Goodにも書いたのですが、もくもく会を開催するだけなら僕らはできるので、もくもく会をどう運営していくか(対外的にどう発信していくかなど）を考えたいと感じた
    * 内輪でやるの？対外的に流入を増やすの？なんの目的で？中にいる人が楽しめたらいいの？誰のためのコミュニティなの？とかとか
* その辺りの方針がないと、意思決定できないというか、議論が無駄に時間がかかって意味ない状況になるなぁと感じました
<br />

### イベント会場への誘導方法
* 建物に入ってから、もくもく会会場までの導線で、迷ったという意見をいただく
    * 動線が作りが弱かったです。すいません。
    * 途中から動線変えたのですが看板が足りなくなって、外で自分が看板代わりの受付していました

**Comment by IkezoeMakoto** [comment]
これ閉じていいやつかな
