### ISSUE TITLE
connpassページを用意する

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/MokuMoku#19]
connpassページを用意する
https://teckup-tokyo.connpass.com/event/125149/preview/

_Originally posted by @IkezoeMakoto in https://github.com/techup-tokyo/MokuMoku/issues/18#issuecomment-476212680_

**Comment by IkezoeMakoto** [comment]
あとアイキャッチ画像用意したい

**Comment by IkezoeMakoto** [comment]
会場はうやまさんが抑えてくれたらしい

**Comment by yumechi** [comment]
[TeckUp]もくもく会#1 https://teckup-tokyo.connpass.com/event/125149/ #teckup

出来てました
