### ISSUE TITLE
打ち合わせ議事録を書く

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#2]
Markdownでいいよね

**Comment by Ushinji** [comment]
GoogleDocumentにてログを残す。疑問点は、ここに書いてください
https://docs.google.com/document/d/1aGKRr3IX7fEZHXPnDe331LkQVK4rsunEB85qF1eSxvk/edit

**Comment by yumechi** [comment]
（Google Drive、スマホからパッと見たいときにめんどいのでやっぱテキストで見たい…）

**Comment by yumechi** [comment]
とりあえず終了にします（Markdownにするのをやるとすれば、適当にやればいいかなと思う）

**Comment by Ushinji** [comment]
# 日時/場所
- 18/09/22(土) 10:00~
- 渋谷のどこか

# もくもく会の前提
## まず何をやるか
  - やる内容はテーマ決める？
  - バラバラで集まってやる？

- 自分がやりたいことにもくもくする
- 講義形式のような、教える ⇄ 教わるの関係は無し
- 自分の興味を持っているもの・やることをもくもく会の前日までに宣言しておく
（スキルシートとかあると誰に何を聞けばいいのかわかるので、そういうの作っておけるといいね）

## やること案
- Alexaハンズオン
- LINEボットのハンズオン
- 技術書を使ったもくもく
- Python入門で新しい言語を触ってみよう！（現エンジニア）
- 機械学習のために基礎から数学をやってみよう（現エンジニアだけど、数学の基礎怪しい）
- railsのチュートリアルやりたい人

# いつやるか？

## どうやって決める？
- 土日がいい
- ひらおさんの予定がタイトなので、ひらお氏の参加可能日を優先したい
    - 平尾さん優先で、一旦10/13(土)を予定日に設定

# 場所決め
- そもそも場所の確保が急務
- 可能な限り無料の場所探したいけど、距離とかも考えたいね
- もし参加費を払うのであれば、何時間いくらまで許容できるか、まずはここのチャンネル参加してる人だけでもいいから認識合わせしたいね

## 吉祥寺
営業開始〜営業終了 : 1,800円/時間
1800円*6時間/8人≒1200円
https://www.instabase.jp/space/2208449178?from_date%5Byear%5D=2018&from_date%5Bmonth%5D=10&from_date%5Bday%5D=13

## ◎池袋駅
12:00〜18:00 : 900円/時間
900円*6時間/8人≒700円〜1200円
https://www.instabase.jp/space/5734983012?from_date%5Byear%5D=2018&from_date%5Bmonth%5D=10&from_date%5Bday%5D=13&from_time=13%3A00&to_time=19%3A00

## 渋谷
池袋の場所取れなかったので、以下の会場に決定

```
■ 予約内容 
プロジェクタ無料の貸し会議室♪ - 【サンク会議室】 
https://www.instabase.jp/space/2212000209

予約番号: 3447387703 
支払方法: クレジットカード 
合計金額: 7,776円（税込）

利用日時: 2018年10月13日(土) 13時00分〜19時00分 
利用料金: 7,776円（税込）

合計金額: 7,776円（税込）
```

# 当日スケジュール
確定案
13:00：スタート。前説、やること共有。もくもくスタート
13:15：もくもくスタート
18:00 〜 成果報告会
18:50：終了
19:00：貴族会開催

## 当日スケジュール決めで出た意見のMEMO
- 午前11:00スタートの場合、開始からの１時間をどう使うか
  - 何をするか、悩ましく感じる時間
  - 何かやること決めるよりも、午後スタートでやってみる
- 途中の休憩はどうするか？
  - 全体で休憩作る？
  - そこは個人の裁量で適宜自由に休憩する(決定事項）
  - 最後に情報共有するから、休憩中の進捗共有は必要ないかと
- 会の進行（だいたい上で決まったからいいや）
  - 集まったら今日やることを宣言したい
  - 終了30分前に進捗報告したい 
  - いろいろ進捗書き込むのもこのSlackでやる？発言量が無限に増える恐れ。無料枠でやっているところへの圧迫

# 連絡・周知方法
- connpassか何かがいいな → slack の general で8人申し込みあれば、なければconnpassで、足りなければ平尾が書く
- 告知を出すときにはSlackの準備完了していたいな
- 進捗とかはどう管理する？ あるいは参加者への連絡。 discord or new slack が有力？
    - 参加メンバーだけでは決められないので、アンケートで聞いて、その結果を元に選定する

# その他のタスク
- 可能なら貴族会のように第○の△曜日☓☓時から☓☓+N時まで、と決める

# 残タスク
- 参加メンバーへの周知
- Generalへ周知(DONE)
- 8人まで埋まらない場合、Conpassへ周知(Block)
- 参加メンバーの確定
  - 開催１週間前の10/7(日)
- 使用チャットツールの選定
  - 10月1日に再興する。
```
[質問です]みんなチャットツールは何が好き？（こんどもくもく会で使うチャットツールの参考にします）の結果から考える
```

**Comment by yumechi** [comment]
close されたissue は存在を忘れがちなので、wiki か リポジトリへファイルをコミットする運用を取りたいです
