### ISSUE TITLE
もくもく会の司会進行用のスライド作成

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#21]
## やったこと
- もくもく会の司会進行用のスライド作成
https://docs.google.com/presentation/d/11pHdYfVAioX4z5vM8TI3WXqmV2FrndKcRPNMXCSwjuY/edit?usp=sharing

## 確認して欲しいこと
- 全体の流れ
- 「TechUp」の `説明`について
  - 説明の表現に誤りがないか？
  - 内容不足が無いかどうか？
  - 運営内で、認識の相違がないか？

**Comment by yumechi** [comment]
* 全体の流れはOK
* TechUpの説明について
    * ツイッターハッシュタグ `#techup` でお願いしておく
        * （会場のオペになるけど） `#techup` を貼っとく
    * いつかはそのうちみんなでなにか作りましょう！ みたいなのを書くのありかも
        * 胡散臭さはあるかもしれないのでお任せ
* page 9
* `わからないことがあったらSlackを利用！` はちょっと意見を聞きつつ考えたい
    * Slackは運営しか使わない想定と考えてた
    * Twitterハッシュタグとか、口頭でHelp？
    * あるいは参加者用のWorkSpaceを用意するとか

**Comment by IkezoeMakoto** [comment]
ありがとうございます！内容確認しました。

当日SlackについてはSlackにも書きましたが

```
少なくともここのSlackは運営のみのワークスペースと考えていました。
最初のうちはtwitterハッシュタグで交流、成果物の共有などはしてもらえばいいかなと思います。
参加者が増えてきたりして参加者からSlackスペースが欲しいという意見が出てきたらTechUpUsersみたいなワークスペースを作ればよいかと
```
という意見です。

**Comment by Ushinji** [comment]
slackにも書きましたが、
当日のコミュニケーション手段は、自分も不透明だったので、コメント頂けてありがたい！

では、もくもく会中のコミュニケーションは、
- twitterハッシュタグ付きで呟く
- 直接質問する
のように述べておく感じですかね。

その、心持ちとしては、
「質問、交流するのおっけーだけど、特段ルールとか無いので好きにしてくれ。
一応twitterハッシュタグあるから呟くと、誰か助けてくれるかも！または、直接周りに質問するのええで！」

みたいな感じが参加者に伝わればいいすかね。

slackは参加者からの意見が多ければ、都度検討というスタンスで良いかと！

**Comment by yumechi** [comment]
とりあえず今回は会場説明をうまくやれたことですし、Closeしましょう。
