### ISSUE TITLE
[第1回] もくもく会振り返りイベントを立てる

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#22]
Ref: #18

**Comment by yumechi** [comment]
# はじめに

このイベントは[[TeckUp]もくもく会#1](https://teckup-tokyo.connpass.com/event/125149/)の振り返りイベントです。

もくもく会の開催を通して学んだこと、わかったこと、反省すべきこと、そして次にやるべきことを検討していきます。

# 検討内容

* 今回のもくもく会の振り返り
    * 準備段階
    * 当日運営
* 次回に向けての課題点の洗い出し
* 次回の日時決定・場所候補の選定

# 日時・場所

* 日時: 4/26(金) 20:00〜22:00 予定
* 場所: 未定（前回プランニング時点ではサイゼリア等に集まっていました、ミーティングスペース等の場所をお貸しいただけるのであれば[twitter: @teckup_tokyo](https://twitter.com/teckup_tokyo)宛にDMいただけますと幸いです）
    * 仮に場所がサイゼリアになると食事代は自費です
    * 確定次第、Connpassのメッセージ機能で募集をかけます

# こんな人に来てほしい

* もくもく会・LT会の運営に興味がある
* 技術的になにかを一緒にやる場所・盛り上がれる場所を作りたい
* 裏方から人の成長を支えたい

**Comment by IkezoeMakoto** [comment]
提案ありがとうございます！

振り返りイベントを公開でやることの意義についてはぼんやり理解はあるのですが、
具体的なメリット・デメリットが腹落ちしておらず、そこの認識を揃えておいたほうがいい気がしました。

>次回の日時決定・場所候補の選定

これは振り返りイベントを公開でやるなら振り返りイベントの中でやる必要はないのかなと思いました。
（参加者を募る目的、参加者の参加目的にもよると思います）

**Comment by Ushinji** [comment]
提案ありがとうございます。概ね記事の内容は良いと思います。

一つ提案したいのが「この振り返りにイベントに参加できる人は、前回のもくもく会に参加した人に限る」という点です。理由は、このイベントの目的が「振り返り」(ですよね？)であり、当然もくもく会に参加した人でないと振り返りはできないので、イベントの目的からズレる思うからです。

どうでしょうか？

**Comment by Ushinji** [comment]
> 次回の日時決定・場所候補の選定

> これは振り返りイベントを公開でやるなら振り返りイベントの中でやる必要はないのかなと思いました。（参加者を募る目的、参加者の参加目的にもよると思います）

こちらは自分も同意です。なので、わざわざ記載はしなくて良いかと思います。

ただ「書かないだけで、別に時間が余ったらやっても良いかと」と思うぐらいの気持ちです。

**Comment by yumechi** [comment]
Connpassに乗せるのは今はやめとくかって気持ちになってきました。（チャットとかで意思疎通ができるほど、会のコンセプト等も固められていない段階だと思います。振り返りイベントをConnpassで立てるのも意思疎通がうまく行ってからでしょうね）

残念ですが、今回は見送ります。そのうちやろうってことを考えるときにやればいいんじゃないでしょうか。

クローズします。
