### ISSUE TITLE
Connpassのグループ紹介ページを書く

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#27]
記載されていないため。作成する。

**Comment by yumechi** [comment]
仮版を書いた。もう少しグループに関しての説明文章を作成したい。
ので、確認して確認してほしいです。

https://teckup-tokyo.connpass.com/

**Comment by IkezoeMakoto** [comment]
よさそう

**Comment by yumechi** [comment]
とりあえずもうこれで。修正があれば issue なしで適宜やっていけばいいと思う。（1ヶ月に1回くらいはdiff撮ったほうがいいかもしれない）
