### ISSUE TITLE
ユーザー交流用の場所を考える

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#28]
* Slack
* Discord

くらいが考えられる。ほかはなにかいい感じのあるかな。個人的にソースコードが読みにくいLINEはNG。

**Comment by yumechi** [comment]
Gitterもありかも

**Comment by yumechi** [comment]
https://gitter.im/zoe302/random
謎の場所

**Comment by IkezoeMakoto** [comment]
割とありかもしれないっすね
やるって判断なったらorgnizationと連携して作るのが良さげ

**Comment by tamanobi** [comment]
すでに Gitter に決まっているのでクローズ
