### ISSUE TITLE
次回の計画

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#3]
* 12/8 予定
* 場所未定

**Comment by yumechi** [comment]
* 12/16 
* アディッシュ様借りる？

**Comment by Ushinji** [comment]
12/16 12:00~19:00 アディッシュのセミナールームは一旦押さえました。
部屋のキャパ的に、ゆったり作業できるのは20人ぐらい。

**Comment by yumechi** [comment]
できた
