### ISSUE TITLE
[第1回] 振り返り

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#30]
やる
ref: #18

**Comment by yumechi** [comment]
僕はYWTで書きます。

# Y

* コミュニティとして初のイベントができた
* 予定通り開催できた。大きな問題はなかった。
* 発表交流はやってよかった
* Twitterハッシュタグを使えた

# W

* ハッシュタグは有効に活用できていると感じる。今後も続けたい。
* 発表交流も今回の人数であれば実施するの多いにあり
* 進捗が出せるのは気持ちが良い
* SlackにTwitterの情報流すのはキャッチしやすくて良い


# T

* コミュニティーのネーミングの由来とかを詰めるべき
    * とりあえずリネームだけ完了したが、結局どうなった？
    * 最初の説明スライドでも使いたいし、Connpassやホームページ等にも生かしていきたい
* 身内感をもう少し排除したい
    * 初回ということもあり、もともとの知り合いが多かった
    * 顔を知ってる人に話を振りがちな傾向であるように思えるので改善ポイント
* 懇親会参加者の管理可視化
    * 僕視点から見えてきづらかった
    * 8人で予約して5人しかいなかったのは why ？
* 僕が時間どおりに来る
    * マンショントラブルとかちょっと想定外だったけど、もう少し早く出れるように努力します

**Comment by IkezoeMakoto** [comment]
### やったこと
* Twitterハッシュタグ利用
* TeckUpでの開催
* もくもく会運営初参加（あまり仕事してないけど）
* TeckUpコミュニティの発足

### 良かったこと
* TeckUpでの初イベントにもかかわらずはじめての人も参加してくれていた
    * connpassの分析を見れていないが、connpassやtwitterでの拡散が原因か？
* ハッシュタグでのコミュニケーションが結構うまく行ってそう
    * 多分最初の導入で説明したこと、前のホワイトボードに書いていたこと、みんなが進捗を上げてくれていたことが起因
* 当日までのタスクを棚卸ししていたので棚卸ししていたものに関してはつつがなく進捗した
* クロージングでの進捗報告と承認し合う雰囲気
    * これも導入で会の目的などを話して場作りができていたおかげかと

### 課題
* 棚卸ししていたタスク外のものの対応フロー
    * 前日リマインドメッセージ、懇親会の人数確定及び予約
* 遅れて参加するメンバーの把握
* 飲食持ち込み可等の明記
* 参加者の満足度がわからない

**Comment by Ushinji** [comment]
### 良かったこと
- 第一回を無事に開催！
- 平尾さんのGithub, Twitter, Gmail, Slackなどなど、インフラ整備まじ感謝！
- また参加したいという声があった(よかった)
- 当日の会の説明などのスライドについては、事前にメンバー内でレビュー・認識揃えができた！

### 続けた方が良いこと(keep)
- Twitterのハッシュタグが結構利用されていたので、参加者同士で互いの進捗を見ることができた

### 課題に感じたこと(Problem)
- 事前メールの文面ミス
  - 作った人以外の確認をすっ飛ばしてメールを送ったのが問題
- 「 teckupの意味が分からなかった」と何人かに聞かれた
- 開催までの事前準備で互いに認識共有がズレてた(teckupの名前ですね)
 - 互いの進捗について、相互確認ができていない部分が多かった(できている部分はあった)

### 次に取り組むアクション(Try)
<みんなで決めましょう!>

**Comment by Ushinji** [comment]
## 定量的な振り返り

* conpass統計
→ https://connpass.com/event/125149/stats/

### 参加者
- 申し込み数：11人（キャンセル:5人)
- 参加者数：10人
    - 一般：7人(1人は申し込み無し参加(O氏))
    - 運営：3人
- 参加状況
  - スタートから参加(13時)：7人
  - 途中参加：3人
- 懇親会参加
  - 参加者：5人

**Comment by yumechi** [comment]
みなさんありがとうございました。

次に行っていくアクションとしては、次の運営MTGで決めていきたい気持ちがあります。ちょっと僕の方で棚卸しして、運営MTGでやることを考えてみます。

**Comment by yumechi** [comment]
ザクッとカテゴリごとのまとめです。で、次の運営MTGでやることはまとめるので、この issue はクローズします。

# 運営系
## Y
* イベントが運営できた
* twitterハッシュタグはいい感じ
* コミュニティ発足
* スライドなどについては、レビュー認識揃えができた
* Slack, twitter, Gmail, GitHubとインフラ面を整えた効果は大きい

## W
* ハッシュタグは有効活用できている
* 棚卸しできていたものについては、しっかりと消化できた

## T
* TeckUpのネーミングや由来が詰められていない
* イベント参加者（もくもく会、懇親会両方）について管理が可視化されていない
    * 遅れて参加する人の考慮
* 棚卸しに漏れがあり、フォローをどうするか
* 事前メールミス
* 


# 当日系
## Y
* また参加したいという声があった :+1: 
* 発表交流はやってよかった

## W
* 発表交流は継続したほうが良さそう
* 進捗出せるのは良いこと
* TeckUpはじめてのイベントで、はじめての人が来てくれたのは良い

## T
* 飲食持ち込み可否は会場にも書いておくべき
* 満足度が図りづらい
