### ISSUE TITLE
[第2回] 当日のスタッフの仕事一覧出し、および担当決め

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#38]
# 内容
- 当日のスタッフの仕事一覧出し、および担当決め

# 期限
- なるはや。前日まで。

**Comment by IkezoeMakoto** [comment]
一旦パッとでるもの書いておきます。後で追加するかも
- オープニング、クロージングの司会
- 会場案内(要社員)
- 会場準備(2~3人, 重複可)

**Comment by Ushinji** [comment]
このタスクについては、IkezoeMakotoさんが出して頂いた仕事に、各自アサインするで良いと思います。

> オープニング、クロージングの司会

これ、前回自分がやったので、やります。

> 会場準備(2~3人, 重複可)

これ、スタッフ枠で参加している人みんなでやりましょう。

**Comment by IkezoeMakoto** [comment]
ありがとうございます！

**Comment by yumechi** [comment]
テンプレ化するところまで行きたい（この件自体はクローズでも良さそう）

**Comment by IkezoeMakoto** [comment]
issue化したのでクローズ
