### ISSUE TITLE
[第2回] 会の命名についての説明

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#39]
# 内容
- 会の命名についての説明が不十分なので、その説明を言語化する
- 具体的に以下の場所で使用するので、それに合わせて文言を考える
  - 当日のガイダンスでの発表資料
  - conpassページでの「会の説明」

**Comment by Ushinji** [comment]
こちらについて、自分がやります。

タスクとしては、
- @Ushinji が、内容を考える
- @yumechi さん、 @IkezoeMakoto さん がレビューする

です。

**Comment by IkezoeMakoto** [comment]
ありがとうございます！助かります！

**Comment by Ushinji** [comment]
## やったこと
@IkezoeMakoto @yumechi 
一旦、conpassに掲載する用の「「TeckUp」名前の由来について」文言を作成しました。

- 認識はあっているか？
- 表現は正しいか？

という点を確認ください。


## 「TeckUp」名前の由来について

「TeckUp」は、技術や専門領域に縛られず、成長したいと思う人たちが集まるコミュニティです。

「TeckUp」という名前は、技術(Technology)の「Tech」と成長を表す「Up」を組み合わせることで、「技術的に成長する人の集まり」という意味が込められています。

また「Teck」とあえて表現している部分は正規表現の「.+」を表しており、これは「専門領域に縛られず、参加者のみなさんがそれぞれイメージした言葉を自由に表現してほしい」という意味が込められています。

**Comment by yumechi** [comment]
（これクローズしたら下記もクローズしておいてほしい）

https://github.com/teckup-tokyo/teckup-tokyo.github.io/issues/2

**Comment by yumechi** [comment]
ありがとうございます。前半部分は良いと思います。

> また「Teck」とあえて表現している部分は正規表現の「.+」を表しており、

（正規表現自体がちょっとソフトウェアエンジニアよりっぽい表現なので）具体的な例をあげつつ説明したほうが良いかと思います。雑に思いついたものでは

`Kick up 、 back up、 pick up など、様々な「ck」を表現しており` みたいな感じ？

**Comment by Ushinji** [comment]
なるほどーー確かに。何か違和感あるなと思っていたのですが、正規表現の表し方は確かに！と思いました！あざっす！

でも、今になって冷静に考えると、 `様々な「ck」` も違和感ありますね。「なんだよ様々なck」って笑

それを踏まえて、修正。

## 修正案

「TeckUp」は、技術や専門領域に縛られず、成長したいと思う人たちが集まるコミュニティです。

「TeckUp」という名前は、技術(Technology)の「Tech」と成長を表す「Up」を組み合わせることで、「技術的に成長する人の集まり」という意味が込められています。

また「Teck」とあえて表現している部分は、「Tech Up」という言葉を、「Kick up」や「Pick up」、「Back up」などの自分が思う様々な言葉として表現できることを表しており、これは「専門領域に縛られず、参加者のみなさんが多様性を尊重し、それぞれイメージした言葉を自由に表現してほしい」という意味が込められています。

**Comment by yumechi** [comment]
![LGTM](https://lgtmoon.herokuapp.com/images/18714)

**Comment by IkezoeMakoto** [comment]
今見ました！いいと思います！ありがとうございます！

**Comment by Ushinji** [comment]
あざっす！

あとは、会の最初のガイダンスの説明資料にも、上の会の命名の話を追加します

**Comment by Ushinji** [comment]
@IkezoeMakoto @yumechi 

今回考えた会の命名を踏まえて、もくもく会当日に使用するスライドを作成しました。
以下のスライドの「会の説明」の部分を確認いただき、何かあればコメントください。

https://docs.google.com/presentation/d/1TPypUiFDiypI3Apdrpiwx2NWWGz4Z0Uk4GqCIc4v2og/edit#slide=id.g560bf767d0_0_27

**Comment by yumechi** [comment]
カラーリングが良いですね

![LGTM](https://lgtmoon.herokuapp.com/images/21703)

**Comment by yumechi** [comment]
クローズして良さそうなのでクローズ
