### ISSUE TITLE
[第2回] 懇親会の予約

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#40]
# 内容
- 懇親会の予約
  - 「もくもく会」で「懇親会参加」の人数を調べる
  - 近くのお店に予約

**Comment by IkezoeMakoto** [comment]
現時点での懇親会参加で回答している人11人

**Comment by IkezoeMakoto** [comment]
一番近いトリキは”いつものトリキ”

**Comment by Ushinji** [comment]
では、いつものトリキに11人で予約します。

**Comment by IkezoeMakoto** [comment]
あざます！

**Comment by Ushinji** [comment]
予約DONEです。
- 人数: 11人
- 日時: 6/15(土) 19:00~21:00
- 場所: いつものトリキ

なので、Closeします
