### ISSUE TITLE
[第3回] もくもく会

### ISSUE THREAD

**Issue by IkezoeMakoto** [teckup-tokyo/MokuMoku#46]
次回日程を考える
https://chouseisan.com/s?h=6fa5d8f39ce84052bfae3b55c00c44eb

_Originally posted by @IkezoeMakoto in https://github.com/teckup-tokyo/MokuMoku/issues/42#issuecomment-502702058_

**Comment by IkezoeMakoto** [comment]
やること上げていく

**Comment by IkezoeMakoto** [comment]
前日リマインド

**Comment by IkezoeMakoto** [comment]
当日役割決め

- オープニング、クロージングの司会
- 会場案内(要社員)
- 会場準備(2~3人, 重複可)

**Comment by IkezoeMakoto** [comment]
懇親会手配

**Comment by IkezoeMakoto** [comment]
前回の振り返りからのNAとか見なくていいんだっけ？（わすれた

前回の振り返り参照
https://github.com/teckup-tokyo/MokuMoku/issues/42

**Comment by yumechi** [comment]
> 懇親会手配

巻き取ります。

> 前日リマインド

おまかせしたい。。。（前日は予定があって、時間が遅くなるため）

当日は頭の中で会場関係の @Ushinji が担当したほうがスムーズだなと思ってます。当日の会場の準備はとりあえず全員でとかでも良さそう…（もくもくの運営は4人なので、多くもなく少なくもなくで回りそう

**Comment by yumechi** [comment]
NA読み直した。この辺が中途半端に浮いてて、今回間に合いそう。


* コンビニとか休憩タイムの導入
* 会場案内をConnpassメッセージで送る
* gitterの導入（作って結局放置気味なので色々テコ入れしないと難しそう、延期濃厚）

**Comment by Ushinji** [comment]
> オープニング、クロージングの司会
> 会場案内(要社員)
> 会場準備(2~3人, 重複可)

これやります。

**Comment by DAdDY0055** [comment]
>前日リマインド

これやります(connpassより)

**Comment by DAdDY0055** [comment]
当日は開始ギリギリか少し遅れそうなので、すみませんが当日の会場準備や受付は他の方にお願いしたいです。。

**Comment by IkezoeMakoto** [comment]
NA的なやつからの抜粋していく

**Comment by IkezoeMakoto** [comment]
入場案内を当日全体にメッセージ&compassページのコメントで流す

**Comment by IkezoeMakoto** [comment]
会の進行回りの改善

* 写真等の撮影権限についての確認・会社ブログとかへの流用等のコミュニケーション
    * 気にしすぎかもしれない
    * 会場として使わせていただいている企業には、会場として利用いただきましたという事例を書いてもらえるといいかも？
    * あと写真撮影するならプライベートならOK、ブログに乗せてもOKとかそのあたりの線引を事前周知したい（スライドで）
        * 会場側が無断で写真を上げたりすると、結構後でトラブルになりがち（経験あり）
* 自己紹介のやり方改善
    * スタッフが1島ずつ入って、スタッフが見本を見せる形式で良いかなと
    * 最後の情報共有タイムも同じ島でやりたい
* 写真可否を聞く、ブログの執筆の推奨など(会場提供側的には書いてもらいたい)

**Comment by IkezoeMakoto** [comment]
振り返り材料の収集

* 参加者アンケートを取る
    * 良かったところと悪かったところ聞くだけで良さそう

**Comment by IkezoeMakoto** [comment]
振り返りする

**Comment by IkezoeMakoto** [comment]
完
