### ISSUE TITLE
アンケートの項目検討

### ISSUE THREAD

**Issue by DAdDY0055** [teckup-tokyo/MokuMoku#57]
効果測定できるための項目を作る
→参加者の満足度と、改善ポイントがわかる

・connpassID
・集中できたか

など

**Comment by DAdDY0055** [comment]
前回アンケート
https://docs.google.com/forms/d/15QAMTwmqpq4NoKXskrf8ddtQnonKy8XKM1Tq35WR5Sw/edit

**Comment by DAdDY0055** [comment]
【草案】
1. 年齢
　10代、20代、30代、40代、50代、それ以上

2. 差し支えなければconnpassのIDを入力お願いします(今後の参考にさせていただきます)


3. [TeckUp]もくもく会への参加は初めてですか？

4. イベントを何で知りましたか？
　- connpassで見て
      友人から聞いて
　　SNSで見た

5.  参加に至ったきっかけは何ですか？ →　複数チェック形式にする
  開催場所が近い
  作業する場所が欲しかった
  他のエンジニアとの交流したい
  一人だと集中できないので、みんなでもくもくしたかった
  その他

6. 全体の満足度について
    低い　1〜5　高い
　その理由は(自由記述)

7. しっかりもくもくできましたか
    できなかった　1〜5　できた
　その理由は(自由記述)

8. 次回も参加したいですか
    ぜひ参加したい
　都合が合えば参加したい
　内容による
　参加したくない

　その理由は(自由記述)

9. 【任意】最後に、「今回の会の感想」や「今後のもくもく会に期待すること」など、自由に記入してください。

(参考)
https://form.run/media/contents/enquete/create-enquete/
```
イベントアンケート（セミナー参加者向け）

セミナー参加者向けのイベントアンケートには

セミナーを知った経路
セミナーに対する満足度
次回開催時に参加したいかどうか
次回参加するとしたら何を知りたいか
といった内容を盛り込むと良いでしょう。

また、自由記述欄を設けておくと、具体的な意見を記入してもらえる場合があるので、アンケートの最後の設問にするのがおすすめです。
```

**Comment by DAdDY0055** [comment]
アンケート案作成してみました。
https://docs.google.com/forms/d/15kVKJfi4Yez190fzH1ewQmTkqomIpOT-N6xUnu-07gs/edit

何かおかしな点などないかご意見ください！

(前回からの変更点)
- 自由記述で2. 年代、3. ユーザー名欄を追加
- 5. 参加しようと思ったきっかけを追加
- 6. 満足度についての理由の自由記載欄を追加
- 8. 集中して作業できましたか？、10. 次回も参加したいですか？を追加
- 最後の自由記載欄に「こうだったらもっと良かった」を追記

**Comment by yumechi** [comment]
ありがとうございます。気になった点をコメントします。

* 年代について
    * 一度選択すると未選択に戻せないので、ラジオボタンよりドロップダウンとかにしたほうがいいかなと思いました。
* 「【任意】(差し支えなければ)connpassのユーザー名を教えてください」について
    * 任意、と差し支えなければ、がかぶっているので任意だけで良いと思います
* 「4. 何で知りましたか？」について
    * 「4. このイベントを知ったきっかけについてお教えください」、とかですかね？
* 「5. 参加しようと思ったきっかけは何ですか？」について
    * 「5. 参加しようと思った動機は何ですか？」、とかですかね
    * きっかけは知るタイミングの話で、どういう気持ちで参加しているのかが動機かと思います
* 各種理由は任意回答であるものの、回答する箇所が多く見える印象があるので、メンバー内で少し話しましょう（↑の理由、よりは、「上記、満足度の理由を教えて下さい」とかが個人的には好みですね）
* 「12.【任意】最後に、「今回の会の感想」や「今後のもくもく会に期待すること」「こうだったらもっと良かった」など、自由に記入してください。」について
    * 「12.【任意】今回の感想や、TeckUpに期待すること、改善点などありましたら、ご記入ください」くらいですかね…

**Comment by DAdDY0055** [comment]
ガッツリレビューありがとうございます！

- 年代について
→ドロップダウンにしました

- 「【任意】(差し支えなければ)connpassのユーザー名を教えてください」について
→年代やユーザ名は嫌がる人もいるかと思い、もしよければ・・ぐらいの意味で2重にしてましたが【任意】だけにしておきます。

- 「4. 何で知りましたか？」について
→前までシンプルに短くだったのでそのままにしてましたが、
「4. このイベントを知ったきっかけは何ですか？」ぐらいでどうでしょう？
(お教えくださいだとちょっと仰々しい気がしたのと、他同様`か？`で締めた方が統一感あるかなと)

- 各種理由
→任意なので飛ばせばそんな量ないので良いかなと思い増やしましたが、他の方でご意見あればください。(長くなるので↑にしてましたが、上記、◯◯の理由を教えてくださいといった形に修正しました)

- 「12.【任意】最後に、〜
→イメージしやすいようと色々書いてましたが、長い印象を与えるようなので修正しました。

**Comment by yumechi** [comment]
> 「4. このイベントを知ったきっかけは何ですか？」ぐらいでどうでしょう？

これで良いと思います！

**Comment by Ushinji** [comment]
作成ありがとうございます！
yumechiさんがほとんど書いてくれたので、概ね良いかと！

その上で、一点気になったのが、

> 8. 集中して作業できましたか？
> はい、いいえ、その他

とありますが、「その他」はどういった入力を想定されていますでしょうか？個人的な意見として、この問いに対して、はい、いいえ以外の回答がないと感じたので。もし想定がないのであれば、その他は不要かと思いました。

**Comment by DAdDY0055** [comment]
仰るとおりだいたいはい、いいえで足りると思いましたが、例外的にそれ以外をいれたくなる人がいるかなと思い作りました。

例を出すのであれば、
>微妙(集中できたりできなかったり)

とかですかね。

そういうのは自由記述欄に書いてくれるだろう、ということであれば不要だと思いますし、邪魔であれば消します！

**Comment by Ushinji** [comment]
> 微妙(集中できたりできなかったり)

なるほど。確かにありそう！
であるならば、選択肢よりも横スライド形式で３段階で選ぶ方が、より適切かと思いました。

> 集中できましたか？
> できなかった <-> できたり、できなかったり <-> できた

みたいな感じですかね。

**Comment by yumechi** [comment]
確かにスライドで良さそう。僕ははい、いいえ、で後で理由聞くとかで良いかなと思いました。

**Comment by Ushinji** [comment]
はい、いいえだけにして、あとで理由聞く形式にし、その他を選択肢から外すしますか。このケースがやりたいことを実現でき、かつ一番修正少ないですし。

また、スライドにする場合、中間の文言を考えるのが面倒そうですし(笑)

**Comment by DAdDY0055** [comment]
はい、いいえにし、任意で理由を聞く形にしました。

**Comment by DAdDY0055** [comment]
他大丈夫そうなのでこちらでクローズします。
