### ISSUE TITLE
[第四回]ガイダンス資料のアップデート

### ISSUE THREAD

**Issue by Ushinji** [teckup-tokyo/MokuMoku#58]
## What
- [前回の振り返り](https://docs.google.com/spreadsheets/d/10SxAOfHWPjp0_N8z5713iSA-vT4Dpe_AZwrjgrGDV_8/edit?usp=sharing)を踏まえて、ガイダンス資料をアップデートしました。**気になる点や改善点などありましたら、コメントをお願いします。**
  - https://docs.google.com/presentation/d/1dj_9eExf10iJEXQrubjDfkQ3LIlof4n-hgxQT2OU8H4/edit?usp=sharing
- アップデート点をまとめると以下の３点です
  - 1. スケジュールに休憩時間を明記
  - 2. Gitterの説明を追加
  - 3. もくもく会に来た人向けに、はじめに行ってほしいことを説明するスライドを追加
- 以下、具体的なアップデート点です
  - P2. もくもく会に来た人に見せるスライドを用意
    - 来た人がまずはじめに何をするのかを説明(Gitterの自己紹介チャンネルに自己紹介を書く)
  - P14. Gitterの説明を追加
    - Gitterで進捗や困っていることを呟いてもらうように説明
  - P15. もくもく会のスケジュール修正
    - 途中の休憩時間を追加
  - 細かいデザインの修正(どこが変わったか分かるかな？w)

**Comment by yumechi** [comment]
LGTM

**Comment by yumechi** [comment]
開催が終わってる上、特に課題点がなかった認識なので、閉じときます
