### ISSUE TITLE
Connpassとかに宣伝うつ？

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#6]
希望だよ

**Comment by Ushinji** [comment]
さて告知のフォーマット考えますか。ざっと以下の通りですかね。

# はじめに

<要追記：なんかキャッチフレーズ的な何か。>

# 内容

<要追記：今回のもくもく会の説明>

# 開催要項

## 日程

【日時】2018-12-16(日) xx:xx ～ yy:yy（開場xx:xx）</br>
【場所】株式会社アディッシュ セミナールーム</br>
【住所】東京都品川区西五反田1-21-8 (KSS五反田ビル6階 セミナールーム)</br>
</br>
【アクセス】JR山手線 五反田駅西口より徒歩6分</br>
　　　　　　都営浅草線 五反田駅A3・A1出口より徒歩6分</br>
　　　　　　東急池上線 大崎広小路駅より徒歩1分</br>
　　　　　　JR山手線 大崎駅北改札口を出て西口出口より、大崎警察署に向かって山手通り沿い徒歩7分</br>

</br>
【設備】</br>
・フリーWifi</br>
・電源ケーブル</br>
・プロジェクター</br>

## タイムスケジュール

<要追記：ざっと１日のスケジュール>

<要追記：(あれば)懇親会の予定>

## こんな人に来てほしい

<要追記：対象ユーザースペック>

---

# 貴族会とは

毎月第2金曜日の夜、渋谷の貴族が集まる場所で、</br>
会社も職種も超えて互いに交流を深め合う【貴族達】の</br>
**「何か面白いことやりたい！」** という想いから生まれたグループです！</br>

- **[Facebook](https://www.facebook.com/groups/kizokukai/)** や **[Slack](https://join.slack.com/t/kizokukai/shared_invite/enQtMzcyODUzODc4OTk2LWQ0NWUzYzg2MTdkMDI3MjBmNTMxNDlmYzliNGFmM2MzZWRlMDM4NTA0NmI2Nzc5MDM1ODM0N2ZiNDQyZGU2Zjk)** もあります！ 是非ご参加ください！

#### ちなみに

背景の**<span style="color: #F3C108;">黄色</span>**、ロゴの**<span style="color: #B8272E;">赤</span>**、もう[何貴族](https://www.torikizoku.co.jp/)か分かるよねっ！

**参考**

- [判定ツール](http://higashi-dance-network.appspot.com/iromiru/)
- [判定画像](http://blog-imgs-84.fc2.com/b/i/n/binalike/20151108092610c4e.jpg)

**Comment by yumechi** [comment]
良いと思う1

**Comment by yumechi** [comment]
貴族会のページから投稿することをお忘れないよう…！
あとやっぱりテンプレートはリポジトリへファイルコミットする人になりたいです

**Comment by yutonihei** [comment]
タイムスケジュール案ですが、
09:30 運営陣集合、会場準備
10:00-10:20 ガイダンス・軽い自己紹介（人数何人かにもよるけど）
10:20-12:40 午前もくもく（飽きたら外出てもいいけど）
12:40-13:00 報告会
13:00-14:00 一応休憩枠（腹が減っては黙々できぬ）
14:00-14:20 午後ガイダンス・中間報告・自己紹介（午前中来なかった人用にも）
14:20-17:40 午後もくもく（午前中に同じく）
17:40-18:00 報告会

すごいメ○○ルさんもくもくのタイムラインですが体感的に良かったので参考にしてます。
会場が何時まで借りられるかとかは気になります。
上記案だと午中2時間20分・午後3時間20分になっています。

こんな人に来てほしいは
 - プログラミング、どこから手をつけていいか分からない
 - 家だとやる気でない
 - オフラインでもくもくして情報共有したい
 - 困ってる課題を解決してあげたい
 - 参加して貴族になりたい
みたいなのはどうでしょう？

**Comment by yumechi** [comment]
* 継続的にやっていこう
* Connpassに告知だそう
* テンプレートはmdで管理してリポジトリにあげよう

**Comment by yumechi** [comment]
> テンプレートはmdで管理してリポジトリにあげよう

,,,,,,

**Comment by yumechi** [comment]
#13 で続きで。
