### ISSUE TITLE
[第4回] 第4回の振り返り

### ISSUE THREAD

**Issue by yumechi** [teckup-tokyo/MokuMoku#60]
題4回の振り返りと題5回のプランニングをする。

KPT・YWTもこのissueに書く。

**Comment by yumechi** [comment]
日程調整をとりあえず建てる。時間は暫定。

https://chouseisan.com/s?h=1753b30d423c4b97a3fd3177503ad64d

**Comment by yumechi** [comment]
# Y

* Connpassのイベントページやリマインドを担当した
* Twitterでたまに告知
* Connpassの参加者通知用Botを個人的に作った（ https://github.com/yumechi/connpass-notification-bot にある ）


# W

* 前回の振り返りで出ていた場所をイベントページのタイトルに入れる、はわかりやすくてよかった
* 運用上やらなければいけないことが明確になりつつあり、作業する時間が大幅減してる気がする
* LT会から足した文言とかで反映できてないものがある
* 休憩タイムも時間は買ったらちょうど良さそうだった
* 遅刻した人がTwitterのDMしてきて気づくのが遅れた。ぞえさんのフォローにより、なんとか参加してもらえた。（ありがとうございました）

# T

* LT会で改善したものを反映する  #59
* ちょっとユーザー同士の交流が弱めかも？ 発言数が少ない
    * Gitterの運用方法の見直しをしてみたほうが良さげ？
    * もくもく会、LT会ごとにチャンネル増やしてみる？
    * ツイッターのハッシュタグ投稿がほぼなかったので、こちらも活用を考える
* 敷いて言えば、懇親会参加者が少なめだったかも？
    * 皆さんの都合等もあるので仕方ないです
* 実施についてクリティカルな問題は減って来ていると思うので、試してみたい、みたいなことを洗い出してやっていくのもありかも

**Comment by Ushinji** [comment]
## Y(やったこと)
* スライドの修正
    * 会場に来た人が、はじめにすることを追加
    * gitterの説明を追加
* 休憩タイムの時間ハンドリング
    * タイマーで15min測った

## W(分かったこと、気づいたこと)
* 13時時点での参加率高かった
    * 渋谷という立地？
    * 参加者の意識の高さ？
        * 渋谷はもくもくユーザーが多い？
* オフィスが綺麗という感想
    * もくもく作業の集中できたという声
    * オフィス環境と作業の質に相関はある
        * どんな環境だと、もくもく作業の質が上がるか考えてみるも良さそう
* gitterへの自己紹介が多かった
    * 互いにどんな人がいるのか認識でき、みんなでもくもくしている感覚が大きくなる
* gitterの作業コメント少ない
    * みんな集中して取り組んでいる証拠？ 
        * 自分は作業作成に集中しまくっていて、コメントしようという意識にならなかった
    * 誰かが質問などコメントしないと、コメントしようと思わない？

## T(次やること)
* もくもく作業の質を上げる環境要因を挙げてみて、次のもくもく会でやってみる
* 参加者が発言しやすい環境を作るために、運営メンバーは少なくとも発言する
   * 少なくとも進捗発言は、休憩時間前と終了時間前ぐらいに発言する

**Comment by DAdDY0055** [comment]
すみません、振り返りのシートを作成してませんでしたので作成しました。
前回の反省で、結局スプレッドシートに転記するので手間、というのがあったので追加はこちらにお願いします！
https://docs.google.com/spreadsheets/d/1SwhiQsI9U9EucNm5AZe_XsGnTVwR_8pd1PB23IWsrB0/edit#gid=0

(@yumechi さん、@Ushinji さん分は転記済みです)

**Comment by DAdDY0055** [comment]
自分の振り返り、振り返り会の出欠回答も済みです。

**Comment by yumechi** [comment]
やった。次回は12/14で計画
