### ISSUE TITLE
第7回振り返り

### ISSUE THREAD

**Issue by tamanobi** [teckup-tokyo/MokuMoku#76]
一旦、YWTで書きましょう〜。終わったら Issue をクローズします。

**Comment by tamanobi** [comment]
# Y

- 参加した
- もくもく作業した
- 雑談とか相談チャンネルに積極的に書き込んで雰囲気を作った(つもり)

# W

- ゆるくてとてもいい
- 音声とか画面共有が成果発表でできなくなっている人は、テキストチャットに誘導するだけ問題なさそうだと思った
- 前日に準備していたことに気づかなかった
- Twitter アカウントの存在を忘れてツイートするのを忘れた
- Twitter アカウントの存在は知っていたけどパスワードがわからなかった
  - アカウント関連の https://github.com/teckup-tokyo/Management/issues/1 は立てた
- Slack と Discordをどれをどれで話すか決めたほうがよさそう(個人的には現在進行系のイベントはDiscord、運営全般はSlackがよさそう)
- 休憩2回は個人的に区切りがよくて最高だった
- 休憩時に悩み相談ができていたのを見て最高の気持ちになった
- 途中参加OKといいつつ、参加したい人が参加したいときにすばやく対応することが難しそうだった(これは仕方ないけど、ずっとConnpass見ていたりTwitter見ているのは難しいかもと思った)
- 成果発表をグループ分けしたけど、運営がいい感じに仕切っていてよかった(ぼくは二瓶さんの仕切りしかみていないけど)

# T

- やることリストとアサインがないと忘れちゃうので何かしらほしい
- アカウント管理表みたいなものは欲しいね。すくなくとも誰が知っているかとかはどこか見える場所にほしい
- つぎも休憩2回
- SlackとDiscordの位置付けの決定♪
- Twitterでのつぶやきのタイミングをきめておくとよさそう
- 途中参加OKなので、Discordの招待リンクを Connpass に公開しておくのがよさそう(運営とやりとりしなければならないという心理的障害を避ける戦略)
- 音声とか画面共有が成果発表でできなくなっている人は、テキストチャットに誘導するだけにする
- 自己紹介や成果発表をグループ分けするとき、参加者に仕切りを任せたらどうか？　という話があったが、次も運営がやったほうがよさそうだと思った(会をうまく運営されている安心感があるため)

**Comment by yumechi** [comment]
## Y

* 参加した
    * 個人としては前日の体調が崩壊→寝れなくなり事前準備→仮眠して、15時から参加
* 今回も無事にやりきれた
* スライドやアンケートの事前準備
    * 前回から直さないといけないポイントがあったが、前日時点で手を付けられていなさそうだった
    * 土曜日調子が悪くてほぼ寝ていたので、深夜帯に着手した
* 前回のTryの実施
    * ちょいちょい意識してやった気がする
* アカウント周りの意見出しとか
    * 所在が微妙なものがちょいちょいある気がする

## W

* 前回の振り返りであまり触れていなかったが、スライドの課題点がやや浮き彫りに
    * フォントがバラバラだったり etc
    * 自己紹介、成果発表は多分スライドを見せるより、告知チャンネルに貼ったほうがいい
        * 運営による先行した自己紹介 + やり方を確認できるようにしとく、が大事
* 事前準備のシフトが怪しめ
    * 今回誰が司会するの？っていうのも曖昧だった感触
        * 自分は Taku さんが今回やりたい、といっていたのでその流れでやりますか？ って確認を一応とっている
        * 明確に認識できる形にしておきたい
* 会の運営周りと目の前のイベントのバランスは大事
    * 後でやれるものはあとにしとく
    * イベント時は目の前の参加者を盛り上げるのが運営、参加者の動きをよく観察して改善に繋げなければいけない
* アカウント管理周り
    * 色々課題感があるが放置してた
    * 割とこのあたりまで個人で考えるのが限界になりつつある（諸々を兼任している状況で、時間的な作業時間も思考時間も取れるわけじゃない）
        * このコミュニティ運営は今のところ個人的に 5、6番目くらいの優先度
        * ちょっと誰かに任せたい。。。
* ずっとわかってる根本的な課題が残りすぎている
    * issue管理、人員配置、役割など
    * そろそろ向き合うときな気はする
* Discordの権限周りが微妙
    * 多分管理アカウント的なやつがオーナーになったほうがいいと思う
    * 現状の運営権限を追加できるのがオーナーのみなので、特定個人のタスクとなってしまう
    * このあたりあんまりいい管理方法を自分自身が知らないので、 下調べが必要そう
* DiscordとかSlackでの事前の声掛け効果が気になる
    * やるかやらないかでいえば、やったのはすごくよかった
    * 効果は測りづらい部分がある
         * どなたかウォッチしてます？
         * というかアンケートに追加すればよかったなと今更気づく


## T

* issue テンプレをそろそろ誰か…
    * ずっとわかってる課題
* 当日のシフトは事前に確認しときたい…
    * ずっとわかってる課題
* アカウント管理周りをなんとかしたい
    * ずっとわかってる課題
    * 他のところで問題になっていることとしてはGoogleアカウントを複数箇所から複数人ログインすると二段階認証が出ることがある
         * その二段階認証の先は僕になってる（準備する流れでそうなってる）
         * Googleアカウントはあんまり共有に積極的ではないのはこの辺
    * 僕が引き取ってもいいが、流石にこれ以上タスクを持ちたくない感じ
         * CoC, WebSite周りも持ってる
* アンケート項目の精査
    * ずっとわかってる課題
    * 多分、何が取りたいのかが明確になっていなかったり、活用が不十分
    * 根本的に見直しても良いかも（項目の追加、撤廃はどんどんすれば良いと思う）
    * ただ項目数はあまり増えてほしくない。選択肢とか質問を変えるなどでカバーしたい。
* Discord の管理問題
    * アカウント管理とは別トピックレベルで、ロールの管理等の問題があるはず
    * 他のDiscordを使ってるコミュニティあたりから情報収集できないだろうか
* もくもくはそれなりに行けてると思うので、ほかイベントにも転用したい
    * とりあえず配信画面見る形のLTはもう頭の中では行けるなという感触
    * IRTは企画が進んでいたが、よくわかっていない
         * テーブルに集まってガヤガヤ話す形だと思っているので、これがチャンネルごとにガヤガヤということになりそう
         * ほかテーブルの様子を知ることができないので、そのあたりの橋渡しを考える
         * そしてこの形式がIRTなのかはわからない（オンラインのIRTは他の議論形態と実質同義になる場合が存在する？気がしている）

## ほか

あと当日、色々あったとはいえ開始時点にいなかったのは本当に申し訳なかったです。
とはいえ、深夜帯に見ても結構あれだなと思う部分があったので、事前準備パートはもう少し見直しが必要かも。。。
このあたり、オフラインはもっと早めに日付抑えるので上手く行っていたけど、オンラインは準備することが少なく早くできてしまうので、そのプロセスがふわふわしているのかも。YWTに落としにくいのですが、とりあえず書いておきます。

**Comment by DAdDY0055** [comment]
# Y
- connpassページの作成
- 当日の進行

# W
- もくもく会であれば直近でも何とかできる
- (もくもくする場が欲しかったので開催したけどいざやってみると)運営・進行も兼ねているともくもくにあまり集中できない
  - 純粋にもくもくするのであれば気の知れた仲間を誘ってやれば良いのでは？と思ってしまった
- メッセージでURLを送る形式だと、直前に申し込みをする人がいるので気づかないことがあり
  - conpassにURLを貼っておくのが良さそう
- 休憩時間は自分一人が喋ってるだけなことも多々あってしんどかった
- 相談チャンネルは使われなかった
  - 休憩時間で質問はあった

# T
- TeckUpの今後や目指す方向を再考した方が良さげ
  - コミュニティを大きくしたい？個々の技術アップを目指すのであれば運営の仕組みについてあれこれ整備するのは意味が薄いように思える

**Comment by tamanobi** [comment]
アンケート見直してみて……。

みんな満足している。集中して作業はできている。
teckupもくもく会は交流も目的にしているため、「交流できましたか？」という質問項目があってよさそう。

**Comment by tamanobi** [comment]
アンケートのconnpass の名前を聞く欄はDiscordのユーザー名の方が良いのでは？？ by yumechi さん

**Comment by yumechi** [comment]
閉じられていないので閉じます。みなさんありがとう。
